# -*- coding: utf-8 -*-
"""final.21

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NNlwiln_otYDhyK43L7b8hPuagthNkwc
"""

print("สวัสดีสุดหล่อ")
import random

print("เกมทายตัวเลข 1 ถึง 10")
secret = random.randint(1, 10)
guess = int(input("ทายตัวเลข (1-10): "))
if guess == secret:
    print("ถูกต้อง!")
else:
    print("ผิด! คำตอบคือ", secret)

print("พัฒนาโดย ศุภณัฐ แม่งศรี")